name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  IMAGE_NAME: rziankins/testing_dev_stend
  TAG: ${{ github.ref_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag or commit message
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          if [[ "${GITHUB_REF}" =~ ^refs/tags/v([0-9]+\.){2}[0-9]+$ ]]; then
          VERSION=${BASH_REMATCH[1]}
          else
            VERSION="1.0.0"  # Вручную зададим версию, если тег не найден
          fi
          
          if [[ -z "$VERSION" ]]; then
            echo "No version found in the commit message or tag"
            exit 1
          fi
          VERSION=${VERSION//[[:space:]]/}  # Remove any spaces
          echo "Using version: $VERSION"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}

  deploy:
    needs: build-and-push
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in the working directory
        run: |
          ls -la

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.21.0'

      - name: Extract version from tag or commit message
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          if [[ "${GITHUB_REF}" =~ ^refs/tags/v([0-9]+\.){2}[0-9]+$ ]]; then
            VERSION=${BASH_REMATCH[1]}
          else
            VERSION="1.0.0"  # Вручную зададим версию, если тег не найден
          fi
          if [[ -z "$VERSION" ]]; then
            echo "No version found in the commit message or tag"
            exit 1
          fi
          VERSION=${VERSION//[[:space:]]/}  # Remove any spaces
          echo "Using version: $VERSION"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Replace image tag in deployment.yml
        run: |
          if [ ! -f ./deploy/deployment.yml ]; then
            echo "deployment.yml not found in the current directory"
            exit 1
          fi
          sed -i "s|image: rziankins/testing_dev_stend:.*|image: ${{ env.IMAGE_NAME }}:${{ env.TAG }}|" ./deploy/deployment.yml

      - name: Create kubeconfig
        run: |
          mkdir -p $HOME/.kube/

      - name: Authenticate to Kubernetes cluster
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "${KUBE_CONFIG_DATA}" | base64 --decode > ${HOME}/.kube/config
          kubectl config view
          kubectl get nodes

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./deploy/deployment.yml
          kubectl get daemonsets -n monitoring
          kubectl get pods -n monitoring
          kubectl describe daemonset myapp -n monitoring
          kubectl describe service myapp-service -n monitoring
